; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1-n16r8]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitc1-n16r8
framework = arduino
build_type = debug
build_flags =
    -DTINY_GSM_MODEM_SIM800
    -DDEBUG
lib_deps =
    bblanchon/ArduinoJson@^7.4.2
    knolleary/PubSubClient@^2.8
    vshymanskyy/TinyGSM@^0.12.0
    adafruit/RTClib@^2.1.4
    h2zero/NimBLE-Arduino@^2.2.1

[env:esp32-s3-devkitc-1-n16r8-release]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitc1-n16r8
framework = arduino
build_type = release
build_flags =
    -DTINY_GSM_MODEM_SIM800
lib_deps =
    bblanchon/ArduinoJson@^7.4.2
    knolleary/PubSubClient@^2.8
    vshymanskyy/TinyGSM@^0.12.0
    adafruit/RTClib@^2.1.4
    h2zero/NimBLE-Arduino@^2.2.1
